version: '2'

services:
    zen-examples-php:
        container_name: zen-examples-php
        image: php:7.4-cli-alpine3.12
        volumes:
            - .:/var/www
        working_dir: /var/www
        command: /bin/sh -c "./examples/run.sh"
