version: '2'

services:
    zen-php:
        container_name: zen-php
        image: php:7.4.0-cli-alpine3.10
        volumes:
            - .:/var/www
        command: /bin/sh -c "cd /var/www; php vendor/bin/phpunit"
