name: "Continuous Integration"

on:
  - pull_request
  - push

jobs:
  coding-standards:
    name: "Coding Standards"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install PHP 8.0"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, xml
          coverage: none
          tools: composer:v2

      - name: "Validate composer.json"
        run: php8.0 $(which composer) validate --strict

      - name: "Cache dependencies"
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install dependencies with composer"
        run: php8.0 $(which composer) install --no-interaction --no-progress --no-suggest --ignore-platform-reqs

      - name: "Run PHP CodeSniffer"
        run: php8.0 vendor/bin/phpcs --standard=phpcs.xml

  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install PHP 8.0"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, xml
          coverage: none
          tools: composer:v2

      - name: "Cache dependencies"
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install dependencies with composer"
        run: php8.0 $(which composer) install --no-interaction --no-progress --no-suggest --no-plugins --ignore-platform-reqs

      - name: "Run phpstan/phpstan"
        run: php8.0 vendor/bin/phpstan analyse --level 8 src

  tests:
    name: "Tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-binary:
          - php8.0

        dependencies:
          - lowest
          - highest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install PHP 8.0"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, xml
          tools: composer:v2

      - name: "Cache dependencies"
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install lowest dependencies with composer"
        if: matrix.dependencies == 'lowest'
        run: ${{ matrix.php-binary }} $(which composer) update --no-interaction --no-progress --no-suggest --no-plugins --prefer-lowest --ignore-platform-reqs

      - name: "Install highest dependencies with composer"
        if: matrix.dependencies == 'highest'
        run: ${{ matrix.php-binary }} $(which composer) update --no-interaction --no-progress --no-suggest --no-plugins --ignore-platform-reqs

      - name: "Run unit tests"
        run: ${{ matrix.php-binary }} vendor/bin/phpunit

  code-coverage:
    name: "Code Coverage"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install PHP 8.0"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, xml
          coverage: xdebug
          tools: composer:v2

      - name: "Cache dependencies"
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: "Install dependencies with composer"
        run: php8.0 $(which composer) install --no-interaction --no-progress --no-suggest --no-plugins --ignore-platform-reqs

      - name: "Dump Xdebug filter with phpunit/phpunit"
        run: php8.0 vendor/bin/phpunit --dump-xdebug-filter=.build/phpunit/xdebug-filter.php

      - name: "Collect code coverage with Xdebug and phpunit/phpunit"
        run: php8.0 vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --prepend=.build/phpunit/xdebug-filter.php

      - name: "Download code coverage uploader for Codecov.io"
        run: curl -s https://codecov.io/bash -o codecov

      - name: "Send code coverage report to Codecov.io"
        run: bash codecov -t ${{ secrets.CODECOV_TOKEN }}
